export const reviewsData = [
  {
    id: 1,
    restaurantId: 1,
    title: 'Sinigang That Takes You Home',
    rating: 5,
    reviewer: 'Marco R.',
    reviewerAvatar: 'https://i.pravatar.cc/150?u=marco',
    date: 'Jan 15, 2026',
    body: 'The sinigang here is next level — perfectly sour with fall-off-the-bone pork ribs. Paired it with garlic rice and I was in heaven. Super affordable and generous servings!',
    reviewImage:
      'https://images.unsplash.com/photo-1536489885071-87983c3e2859?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    helpfulCount: 5,
    unhelpfulCount: 1,
    comments: [
      {
        id: 101,
        author: 'Camille S.',
        date: 'Jan 16, 2026',
        body: 'Totally agree! The garlic rice is a must.',
      },
    ],
    ownerResponse: {
      date: 'Jan 16, 2026',
      body: 'Thank you so much for the kind words, Marco! We are thrilled you enjoyed the sinigang. Hope to see you again soon!',
    },
  },
  {
    id: 2,
    restaurantId: 2,
    title: 'Rich Broth and Perfect Gyoza',
    rating: 4,
    reviewer: 'Camille S.',
    reviewerAvatar: 'https://i.pravatar.cc/150?u=camille',
    date: 'Jan 20, 2026',
    body: 'Amazing ramen with rich, flavorful broth. The gyoza is also a must-order. Gets packed during weekends so come early or be ready to wait. Worth every peso.',
    reviewImage:
      'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    helpfulCount: 2,
    unhelpfulCount: 0,
    comments: [
      {
        id: 102,
        author: 'Marco R.',
        date: 'Jan 21, 2026',
        body: 'I tried it last week and you are right about the gyoza!',
      },
    ],
  },
  {
    id: 3,
    restaurantId: 3,
    title: 'Best Unlimited KBBQ in BGC',
    rating: 5,
    reviewer: 'Jolo P.',
    reviewerAvatar: 'https://i.pravatar.cc/150?u=jolo',
    date: 'Jan 22, 2026',
    body: 'Samgyupsal heaven! Unlimited meat with all the side dishes you could want. The staff was super friendly and attentive. Best KBBQ value in BGC for sure.',
    reviewImage:
      'https://images.unsplash.com/photo-1708388064672-6536507fdf6e?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    helpfulCount: 8,
    unhelpfulCount: 2,
    comments: [
      {
        id: 103,
        author: 'Diana L.',
        date: 'Jan 23, 2026',
        body: 'Did you try their cheese dip?',
      },
      {
        id: 104,
        author: 'Jolo P.',
        date: 'Jan 23, 2026',
        body: 'Yes! It was amazing.',
      },
    ],
  },
  {
    id: 4,
    restaurantId: 4,
    title: 'Kare-Kare Like Nanay Used to Make',
    rating: 4,
    reviewer: 'Diana L.',
    reviewerAvatar: 'https://i.pravatar.cc/150?u=diana',
    date: 'Jan 25, 2026',
    body: 'The kare-kare is outstanding — rich, nutty sauce with perfectly tender oxtail. Bagoong on the side is a must. A true taste of classic Filipino cooking.',
    reviewImage:
      'https://images.unsplash.com/photo-1688084403060-3594a4b8ff8d?q=80&w=1632&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    helpfulCount: 3,
    unhelpfulCount: 1,
    comments: [
      {
        id: 105,
        author: 'Elaine V.',
        date: 'Jan 26, 2026',
        body: 'I need to visit this place ASAP.',
      },
    ],
  },
  {
    id: 5,
    restaurantId: 5,
    title: 'Great Views, Pricey Portions',
    rating: 3,
    reviewer: 'Elaine V.',
    reviewerAvatar: 'https://i.pravatar.cc/150?u=elaine',
    date: 'Jan 28, 2026',
    body: 'The sunset views from the rooftop are gorgeous and the cocktails are creative. Food was decent but a bit overpriced for the portion size. Great for photos and date nights.',
    reviewImage:
      'https://images.unsplash.com/photo-1605270012917-bf157c5a9541?q=80&w=1469&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    helpfulCount: 0,
    unhelpfulCount: 0,
  },
  {
    id: 6,
    restaurantId: 6,
    title: 'Smash Burgers Done Right',
    rating: 4,
    reviewer: 'Francis G.',
    reviewerAvatar: 'https://i.pravatar.cc/150?u=francis',
    date: 'Feb 1, 2026',
    body: 'The smash burgers are insane — crispy edges, juicy patty, melted cheese. Their ube milkshake is a game-changer too. Perfect quick bite near the bay.',
    reviewImage:
      'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?q=80&w=1469&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    helpfulCount: 4,
    unhelpfulCount: 2,
  },
  {
    id: 7,
    restaurantId: 7,
    title: 'A Culinary Masterpiece',
    rating: 5,
    reviewer: 'Grace T.',
    reviewerAvatar: 'https://i.pravatar.cc/150?u=grace',
    date: 'Feb 3, 2026',
    body: "Incredible fine dining experience! The degustation menu was a culinary journey through modern Filipino flavors. The chef's plating is absolutely stunning.",
    reviewImage:
      'https://images.unsplash.com/photo-1599458252573-56ae36120de1?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    helpfulCount: 6,
    unhelpfulCount: 0,
  },
  {
    id: 8,
    restaurantId: 8,
    title: 'XLB Worth the Wait',
    rating: 4,
    reviewer: 'Henry C.',
    reviewerAvatar: 'https://i.pravatar.cc/150?u=henry',
    date: 'Feb 5, 2026',
    body: 'The xiao long bao here is consistently perfect — thin wrapper, hot broth inside. Always a long line during mall hours but totally worth the wait.',
    reviewImage:
      'https://images.unsplash.com/photo-1694834589398-27b369c6f7a6?q=80&w=1040&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    helpfulCount: 1,
    unhelpfulCount: 0,
  },
  {
    id: 9,
    restaurantId: 9,
    title: 'Student Budget Champion',
    rating: 4,
    reviewer: 'Ivy M.',
    reviewerAvatar: 'https://i.pravatar.cc/150?u=ivy',
    date: 'Feb 6, 2026',
    body: "Best inasal in Manila, hands down. The chicken is juicy, perfectly charred, and the unlimited rice is a student's dream. Great value for money.",
    reviewImage:
      'https://images.unsplash.com/photo-1592011432621-f7f576f44484?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    helpfulCount: 7,
    unhelpfulCount: 1,
  },
  {
    id: 10,
    restaurantId: 10,
    title: 'Epic Boodle Fight by the Bay',
    rating: 5,
    reviewer: 'Jake D.',
    reviewerAvatar: 'https://i.pravatar.cc/150?u=jake',
    date: 'Feb 7, 2026',
    body: 'The seafood boodle fight was an epic experience! Super fresh catch cooked multiple ways. The view of Manila Bay during golden hour made it even more special.',
    reviewImage:
      'https://images.unsplash.com/photo-1650435489945-96b2b19b943b?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    helpfulCount: 3,
    unhelpfulCount: 3,
  },
  {
    id: 11,
    restaurantId: 1,
    title: 'Decent Food, Slow Service',
    rating: 3,
    reviewer: 'New User',
    reviewerAvatar: 'https://i.pravatar.cc/150?u=newuser',
    date: 'Feb 15, 2026',
    body: 'Good food but service was a bit slow today. The place was packed!',
    reviewImage: null,
    helpfulCount: 2,
    unhelpfulCount: 1,
  },
];

export const restaurantsData = [
  {
    id: 1,
    restaurantName: 'Kubo ni Lola',
    cuisine: ['Filipino'],
    rating: 5,
    restaurantImage:
      'https://images.unsplash.com/photo-1485686531765-ba63b07845a7?q=80&w=1467&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    description:
      'A cozy Filipino comfort food spot serving home-style sinigang, adobo, and sizzling sisig in a rustic bahay-kubo-inspired setting.',
    address: '78 Remedios St., Malate, Manila',
    hours: '10:00 AM - 9:00 PM',
    phone: '+63 2 8523 1234',
    website: 'www.kubonilola.ph',
  },
  {
    id: 2,
    restaurantName: 'Takeshi Ramen House',
    cuisine: ['Japanese'],
    rating: 4,
    restaurantImage:
      'https://images.unsplash.com/photo-1568018508399-e53bc8babdde?q=80&w=1474&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    description:
      'A no-frills ramen bar in Makati serving rich tonkotsu and spicy miso bowls. Famous for its handmade noodles and crispy gyoza.',
    address: 'Greenbelt 3, Ayala Center, Makati, Manila',
    hours: '11:00 AM - 2:00 PM, 5:30 PM - 10:00 PM',
    phone: '+63 2 8856 5678',
    website: 'www.takeshiramen.ph',
  },
  {
    id: 3,
    restaurantName: 'Hansang BBQ',
    cuisine: ['Korean BBQ'],
    rating: 5,
    restaurantImage:
      'https://images.unsplash.com/photo-1647168585205-e56ebb24a669?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    description:
      'Unlimited Korean BBQ with premium meat cuts and an extensive banchan spread. A BGC favorite for groups and celebrations.',
    address: '30th St. cor. 7th Ave., BGC, Taguig, Manila',
    hours: '11:00 AM - 11:00 PM',
    phone: '+63 917 123 4567',
    website: 'www.hansangbbq.ph',
  },
  {
    id: 4,
    restaurantName: 'Lutong Bahay ni Aling Nena',
    cuisine: ['Filipino'],
    rating: 4,
    restaurantImage:
      'https://plus.unsplash.com/premium_photo-1661373053290-bd41968a916a?q=80&w=855&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    description:
      'A beloved hole-in-the-wall serving hearty Filipino classics — kare-kare, bulalo, and laing — just like nanay used to make.',
    address: '432 San Andres St., Malate, Manila',
    hours: 'Open 24 Hours',
    phone: '+63 2 8524 7671',
    website: 'www.lutongbahay.ph',
  },
  {
    id: 5,
    restaurantName: 'Daloy Rooftop',
    cuisine: ['Modern Asian', 'Bar'],
    rating: 3,
    restaurantImage:
      'https://images.unsplash.com/photo-1621275471769-e6aa344546d5?q=80&w=1473&auto=crop&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    description:
      'A trendy rooftop bar and restaurant with stunning Manila Bay sunset views. Known for creative cocktails and Asian fusion small plates.',
    address: 'Ocean Drive, Mall of Asia Complex, Pasay, Manila',
    hours: '5:00 PM - 2:00 AM',
    phone: '+63 917 987 6543',
    website: 'www.daloyrooftop.ph',
  },
  {
    id: 6,
    restaurantName: 'Patty Shack',
    cuisine: ['Burgers', 'Fast Food'],
    rating: 4,
    restaurantImage:
      'https://images.unsplash.com/photo-1564019709518-6182bdabe251?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    description:
      'A casual burger joint by the bay serving smash burgers, loaded fries, and their signature ube milkshake.',
    address: 'Seaside Blvd., SM by the Bay, Pasay, Manila',
    hours: '10:00 AM - 12:00 AM',
    phone: '+63 2 8830 7000',
    website: 'www.pattyshack.ph',
  },
  {
    id: 7,
    restaurantName: 'Mesa Moderna',
    cuisine: ['Modern Filipino', 'Fine Dining'],
    rating: 5,
    restaurantImage:
      'https://plus.unsplash.com/premium_photo-1661962305366-0c62646fd249?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    description:
      'An upscale restaurant reimagining Filipino cuisine through modern techniques and stunning plating. Perfect for special occasions.',
    address: '5th Ave. cor. 26th St., BGC, Taguig, Manila',
    hours: '6:00 PM - 10:00 PM (Tue-Sat)',
    phone: '+63 2 7795 1234',
    website: 'www.mesamoderna.ph',
  },
  {
    id: 8,
    restaurantName: 'Golden Dumpling House',
    cuisine: ['Chinese', 'Dim Sum'],
    rating: 4,
    restaurantImage:
      'https://images.unsplash.com/photo-1669410647983-ef742ccdfe6d?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    description:
      'A Binondo-inspired dim sum spot serving handcrafted xiao long bao, hakaw, and siomai. Always worth the queue.',
    address: 'SM Mega Fashion Hall, EDSA, Mandaluyong, Manila',
    hours: '11:00 AM - 9:00 PM',
    phone: '+63 2 8831 9999',
    website: 'www.goldendumpling.ph',
  },
  {
    id: 9,
    restaurantName: 'Ihaw-Ihaw Express',
    cuisine: ['Filipino', 'Chicken Inasal'],
    rating: 4,
    restaurantImage:
      'https://images.unsplash.com/photo-1600555379765-f82335a7b1b0?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    description:
      'The go-to spot for chargrilled chicken inasal with unlimited rice. Fast, flavorful, and incredibly budget-friendly.',
    address: 'Robinsons Place Manila, Pedro Gil St., Ermita, Manila',
    hours: '9:00 AM - 10:00 PM',
    phone: '+63 2 8536 9000',
    website: 'www.ihawihaw.ph',
  },
  {
    id: 10,
    restaurantName: 'Alon Seafood Grill',
    cuisine: ['Seafood', 'Fine Dining'],
    rating: 5,
    restaurantImage:
      'https://images.unsplash.com/photo-1657485990998-4b6fca3ca696?q=80&w=1471&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    description:
      'A waterfront fine dining restaurant overlooking Manila Bay. Famous for its seafood boodle fight and fresh catch of the day.',
    address: 'CCP Complex, Roxas Blvd., Pasay, Manila',
    hours: '11:30 AM - 2:30 PM, 6:00 PM - 10:30 PM',
    phone: '+63 2 8828 4888',
    website: 'www.alonseafood.ph',
  },
];
