export const reviewsData = [
	{
		id: 1,
		restaurantId: 1,
		rating: 5,
		reviewer: 'Marco R.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=marco',
		date: 'Jan 15, 2026',
		body: 'The sinigang here is next level — perfectly sour with fall-off-the-bone pork ribs. Paired it with garlic rice and I was in heaven. Super affordable and generous servings!',
		reviewImage: 'https://loremflickr.com/600/400/filipino,food?lock=1',
	},
	{
		id: 2,
		restaurantId: 2,
		rating: 4,
		reviewer: 'Camille S.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=camille',
		date: 'Jan 20, 2026',
		body: 'Amazing ramen with rich, flavorful broth. The gyoza is also a must-order. Gets packed during weekends so come early or be ready to wait. Worth every peso.',
		reviewImage: 'https://loremflickr.com/600/400/ramen,japanese?lock=2',
	},
	{
		id: 3,
		restaurantId: 3,
		rating: 5,
		reviewer: 'Jolo P.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=jolo',
		date: 'Jan 22, 2026',
		body: 'Samgyupsal heaven! Unlimited meat with all the side dishes you could want. The staff was super friendly and attentive. Best KBBQ value in BGC for sure.',
		reviewImage: 'https://loremflickr.com/600/400/korean,bbq?lock=3',
	},
	{
		id: 4,
		restaurantId: 4,
		rating: 4,
		reviewer: 'Diana L.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=diana',
		date: 'Jan 25, 2026',
		body: 'The kare-kare is outstanding — rich, nutty sauce with perfectly tender oxtail. Bagoong on the side is a must. A true taste of classic Filipino cooking.',
		reviewImage: 'https://loremflickr.com/600/400/stew,peanut?lock=4',
	},
	{
		id: 5,
		restaurantId: 5,
		rating: 3,
		reviewer: 'Elaine V.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=elaine',
		date: 'Jan 28, 2026',
		body: 'The sunset views from the rooftop are gorgeous and the cocktails are creative. Food was decent but a bit overpriced for the portion size. Great for photos and date nights.',
		reviewImage: 'https://loremflickr.com/600/400/cocktail,rooftop?lock=5',
	},
	{
		id: 6,
		restaurantId: 6,
		rating: 4,
		reviewer: 'Francis G.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=francis',
		date: 'Feb 1, 2026',
		body: 'The smash burgers are insane — crispy edges, juicy patty, melted cheese. Their ube milkshake is a game-changer too. Perfect quick bite near the bay.',
		reviewImage: 'https://loremflickr.com/600/400/burger,fastfood?lock=6',
	},
	{
		id: 7,
		restaurantId: 7,
		rating: 5,
		reviewer: 'Grace T.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=grace',
		date: 'Feb 3, 2026',
		body: "Incredible fine dining experience! The degustation menu was a culinary journey through modern Filipino flavors. The chef's plating is absolutely stunning.",
		reviewImage: 'https://loremflickr.com/600/400/finedining,plating?lock=7',
	},
	{
		id: 8,
		restaurantId: 8,
		rating: 4,
		reviewer: 'Henry C.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=henry',
		date: 'Feb 5, 2026',
		body: 'The xiao long bao here is consistently perfect — thin wrapper, hot broth inside. Always a long line during mall hours but totally worth the wait.',
		reviewImage: 'https://loremflickr.com/600/400/dumplings,dimsum?lock=8',
	},
	{
		id: 9,
		restaurantId: 9,
		rating: 4,
		reviewer: 'Ivy M.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=ivy',
		date: 'Feb 6, 2026',
		body: "Best inasal in Manila, hands down. The chicken is juicy, perfectly charred, and the unlimited rice is a student's dream. Great value for money.",
		reviewImage: 'https://loremflickr.com/600/400/grilled,chicken?lock=9',
	},
	{
		id: 10,
		restaurantId: 10,
		rating: 5,
		reviewer: 'Jake D.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=jake',
		date: 'Feb 7, 2026',
		body: 'The seafood boodle fight was an epic experience! Super fresh catch cooked multiple ways. The view of Manila Bay during golden hour made it even more special.',
		reviewImage: 'https://loremflickr.com/600/400/seafood,feast?lock=10',
	},
];

export const restaurantsData = [
	{
		id: 1,
		restaurantName: 'Kubo ni Lola',
		cuisine: 'Filipino',
		rating: 5,
		restaurantImage:
			'https://loremflickr.com/600/400/restaurant,interior?lock=101',
		description:
			'A cozy Filipino comfort food spot serving home-style sinigang, adobo, and sizzling sisig in a rustic bahay-kubo-inspired setting.',
		address: '78 Remedios St., Malate, Manila',
		hours: '10:00 AM - 9:00 PM',
		phone: '+63 2 8523 1234',
		website: 'www.kubonilola.ph',
	},
	{
		id: 2,
		restaurantName: 'Takeshi Ramen House',
		cuisine: 'Japanese',
		rating: 4,
		restaurantImage:
			'https://loremflickr.com/600/400/finedining,interior?lock=102',
		description:
			'A no-frills ramen bar in Makati serving rich tonkotsu and spicy miso bowls. Famous for its handmade noodles and crispy gyoza.',
		address: 'Greenbelt 3, Ayala Center, Makati, Manila',
		hours: '11:00 AM - 2:00 PM, 5:30 PM - 10:00 PM',
		phone: '+63 2 8856 5678',
		website: 'www.takeshiramen.ph',
	},
	{
		id: 3,
		restaurantName: 'Hansang BBQ',
		cuisine: 'Korean BBQ',
		rating: 5,
		restaurantImage:
			'https://loremflickr.com/600/400/authentic,restaurant?lock=103',
		description:
			'Unlimited Korean BBQ with premium meat cuts and an extensive banchan spread. A BGC favorite for groups and celebrations.',
		address: '30th St. cor. 7th Ave., BGC, Taguig, Manila',
		hours: '11:00 AM - 11:00 PM',
		phone: '+63 917 123 4567',
		website: 'www.hansangbbq.ph',
	},
	{
		id: 4,
		restaurantName: 'Lutong Bahay ni Aling Nena',
		cuisine: 'Filipino',
		rating: 4,
		restaurantImage: 'https://loremflickr.com/600/400/diner,exterior?lock=104',
		description:
			'A beloved hole-in-the-wall serving hearty Filipino classics — kare-kare, bulalo, and laing — just like nanay used to make.',
		address: '432 San Andres St., Malate, Manila',
		hours: 'Open 24 Hours',
		phone: '+63 2 8524 7671',
		website: 'www.lutongbahay.ph',
	},
	{
		id: 5,
		restaurantName: 'Daloy Rooftop',
		cuisine: 'Modern Asian / Bar',
		rating: 3,
		restaurantImage:
			'https://loremflickr.com/600/400/beach,restaurant?lock=105',
		description:
			'A trendy rooftop bar and restaurant with stunning Manila Bay sunset views. Known for creative cocktails and Asian fusion small plates.',
		address: 'Ocean Drive, Mall of Asia Complex, Pasay, Manila',
		hours: '5:00 PM - 2:00 AM',
		phone: '+63 917 987 6543',
		website: 'www.daloyrooftop.ph',
	},
	{
		id: 6,
		restaurantName: 'Patty Shack',
		cuisine: 'Burgers / Fast Food',
		rating: 4,
		restaurantImage: 'https://loremflickr.com/600/400/foodtruck,beach?lock=106',
		description:
			'A casual burger joint by the bay serving smash burgers, loaded fries, and their signature ube milkshake.',
		address: 'Seaside Blvd., SM by the Bay, Pasay, Manila',
		hours: '10:00 AM - 12:00 AM',
		phone: '+63 2 8830 7000',
		website: 'www.pattyshack.ph',
	},
	{
		id: 7,
		restaurantName: 'Mesa Moderna',
		cuisine: 'Modern Filipino / Fine Dining',
		rating: 5,
		restaurantImage:
			'https://loremflickr.com/600/400/turkish,restaurant?lock=107',
		description:
			'An upscale restaurant reimagining Filipino cuisine through modern techniques and stunning plating. Perfect for special occasions.',
		address: '5th Ave. cor. 26th St., BGC, Taguig, Manila',
		hours: '6:00 PM - 10:00 PM (Tue-Sat)',
		phone: '+63 2 7795 1234',
		website: 'www.mesamoderna.ph',
	},
	{
		id: 8,
		restaurantName: 'Golden Dumpling House',
		cuisine: 'Chinese / Dim Sum',
		rating: 4,
		restaurantImage:
			'https://loremflickr.com/600/400/restaurant,exterior?lock=108',
		description:
			'A Binondo-inspired dim sum spot serving handcrafted xiao long bao, hakaw, and siomai. Always worth the queue.',
		address: 'SM Mega Fashion Hall, EDSA, Mandaluyong, Manila',
		hours: '11:00 AM - 9:00 PM',
		phone: '+63 2 8831 9999',
		website: 'www.goldendumpling.ph',
	},
	{
		id: 9,
		restaurantName: 'Ihaw-Ihaw Express',
		cuisine: 'Filipino / Chicken Inasal',
		rating: 4,
		restaurantImage: 'https://loremflickr.com/600/400/streetfood,shop?lock=109',
		description:
			'The go-to spot for chargrilled chicken inasal with unlimited rice. Fast, flavorful, and incredibly budget-friendly.',
		address: 'Robinsons Place Manila, Pedro Gil St., Ermita, Manila',
		hours: '9:00 AM - 10:00 PM',
		phone: '+63 2 8536 9000',
		website: 'www.ihawihaw.ph',
	},
	{
		id: 10,
		restaurantName: 'Alon Seafood Grill',
		cuisine: 'Seafood / Fine Dining',
		rating: 5,
		restaurantImage: 'https://loremflickr.com/600/400/pier,restaurant?lock=110',
		description:
			'A waterfront fine dining restaurant overlooking Manila Bay. Famous for its seafood boodle fight and fresh catch of the day.',
		address: 'CCP Complex, Roxas Blvd., Pasay, Manila',
		hours: '11:30 AM - 2:30 PM, 6:00 PM - 10:30 PM',
		phone: '+63 2 8828 4888',
		website: 'www.alonseafood.ph',
	},
];
