export const reviewsData = [
	{
		id: 1,
		restaurant: 'Al Safadi Restaurant',
		cuisine: 'Lebanese',
		rating: 5,
		reviewer: 'Khalid M.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=khalid',
		restaurantImage: 'https://loremflickr.com/600/400/lebanese,food?lock=1',
		date: 'Jan 15, 2026',
		body: 'Absolutely fantastic Lebanese food. The hummus and mixed grill were cooked to perfection. A great spot to grab dinner after a long day of classes.',
	},
	{
		id: 2,
		restaurant: 'Zuma Dubai',
		cuisine: 'Japanese',
		rating: 4,
		reviewer: 'Sarah T.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=sarah',
		restaurantImage: 'https://loremflickr.com/600/400/sushi,japanese?lock=2',
		date: 'Jan 20, 2026',
		body: 'Great atmosphere and the black cod is a must-try. It gets quite busy on the weekends, so make sure to book in advance. A bit on the pricey side but worth it for a special occasion.',
	},
	{
		id: 3,
		restaurant: 'Sonamu Korean Restaurant',
		cuisine: 'Korean BBQ',
		rating: 5,
		reviewer: 'Jimin P.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=jimin',
		restaurantImage: 'https://loremflickr.com/600/400/korean,bbq?lock=3',
		date: 'Jan 22, 2026',
		body: 'The best Korean BBQ in the city! The meat cuts are premium, and the side dishes keep coming. They even played some of my favorite K-pop tracks in the background, which was a huge plus.',
	},
	{
		id: 4,
		restaurant: 'Ravi Restaurant',
		cuisine: 'Pakistani / Indian',
		rating: 4,
		reviewer: 'David R.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=david',
		restaurantImage: 'https://loremflickr.com/600/400/curry,naan?lock=4',
		date: 'Jan 25, 2026',
		body: 'An absolute institution. The butter chicken and garlic naan are unmatched for the price. It’s no-frills, but the flavor is incredible.',
	},
	{
		id: 5,
		restaurant: 'Koko Bay',
		cuisine: 'Asian / Continental',
		rating: 3,
		reviewer: 'Elena V.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=elena',
		restaurantImage: 'https://loremflickr.com/600/400/cocktail,beach?lock=5',
		date: 'Jan 28, 2026',
		body: "The views of the Marina are stunning, especially at sunset. However, the service was a bit slow, and the food didn't entirely live up to the hype. Good for photos, though.",
	},
	{
		id: 6,
		restaurant: 'SALT Kite Beach',
		cuisine: 'Burgers / Fast Food',
		rating: 4,
		reviewer: 'Fahad L.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=fahad',
		restaurantImage: 'https://loremflickr.com/600/400/burger,fries?lock=6',
		date: 'Feb 1, 2026',
		body: 'You can never go wrong with their sliders and lotus milkshakes. Perfect place to chill by the beach when the weather is nice.',
	},
	{
		id: 7,
		restaurant: 'CZN Burak',
		cuisine: 'Turkish',
		rating: 5,
		reviewer: 'Grace K.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=grace',
		restaurantImage: 'https://loremflickr.com/600/400/kebab,turkish?lock=7',
		date: 'Feb 3, 2026',
		body: 'An unforgettable dining experience! The portions are massive, and the presentation is a show in itself. The kunefe for dessert is highly recommended.',
	},
	{
		id: 8,
		restaurant: 'Din Tai Fung',
		cuisine: 'Taiwanese / Dim Sum',
		rating: 4,
		reviewer: 'Henry W.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=henry',
		restaurantImage: 'https://loremflickr.com/600/400/dumplings,dimsum?lock=8',
		date: 'Feb 5, 2026',
		body: 'Consistent quality as always. The soup dumplings (Xiao Long Bao) are the reason I keep coming back. Be prepared to wait in line if you go during peak mall hours.',
	},
	{
		id: 9,
		restaurant: 'Operation: Falafel',
		cuisine: 'Middle Eastern Street Food',
		rating: 4,
		reviewer: 'Irene P.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=irene',
		restaurantImage: 'https://loremflickr.com/600/400/falafel,wrap?lock=9',
		date: 'Feb 6, 2026',
		body: 'Solid, reliable street food. The classic falafel wrap hits the spot when you need a quick, satisfying bite while studying or working late.',
	},
	{
		id: 10,
		restaurant: 'Pierchic',
		cuisine: 'Seafood / Fine Dining',
		rating: 5,
		reviewer: 'Jack C.',
		reviewerAvatar: 'https://i.pravatar.cc/150?u=jack',
		restaurantImage:
			'https://loremflickr.com/600/400/seafood,finedining?lock=10',
		date: 'Feb 7, 2026',
		body: 'Breathtaking views of the Burj Al Arab and phenomenal seafood. The tasting menu was an incredible culinary journey. Perfect for a very special evening out.',
	},
];
