export const reviewsData = [
	{
		id: 1,
		restaurant: 'Restaurant 1',
		rating: 4,
		reviewer: 'Alice M.',
		date: 'Jan 15, 2026',
		body: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Consectetur adipiscing elit quisque faucibus ex sapien vitae. Ex sapien vitae pellentesque sem placerat in id. Placerat in id cursus mi pretium tellus duis. Pretium tellus duis convallis tempus leo eu aenean.',
	},
	{
		id: 2,
		restaurant: 'Restaurant 2',
		rating: 3,
		reviewer: 'Brian T.',
		date: 'Jan 20, 2026',
		body: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Sit amet consectetur adipiscing elit quisque faucibus ex. Adipiscing elit quisque faucibus ex sapien vitae pellentesque.',
	},
	{
		id: 3,
		restaurant: 'Restaurant 3',
		rating: 5,
		reviewer: 'Carla S.',
		date: 'Jan 22, 2026',
		body: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Elit quisque faucibus ex sapien vitae pellentesque sem. Sem placerat in id cursus mi pretium tellus. Tellus duis convallis tempus leo eu aenean sed. Sed diam urna tempor pulvinar vivamus fringilla lacus. Lacus nec metus bibendum egestas iaculis massa nisl. Nisl malesuada lacinia integer nunc posuere ut hendrerit.',
	},
	{
		id: 4,
		restaurant: 'Restaurant 4',
		rating: 4,
		reviewer: 'David R.',
		date: 'Jan 25, 2026',
		body: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Amet consectetur adipiscing elit quisque faucibus ex sapien. Quisque faucibus ex sapien vitae pellentesque sem placerat. Vitae pellentesque sem placerat in id cursus mi.',
	},
	{
		id: 5,
		restaurant: 'Restaurant 5',
		rating: 2,
		reviewer: 'Elena V.',
		date: 'Jan 28, 2026',
		body: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Faucibus ex sapien vitae pellentesque sem placerat in. Cursus mi pretium tellus duis convallis tempus leo. Aenean sed diam urna tempor pulvinar vivamus fringilla. Nec metus bibendum egestas iaculis massa nisl malesuada. Integer nunc posuere ut hendrerit semper vel class. Taciti sociosqu ad litora torquent per conubia nostra. Himenaeos orci varius natoque penatibus et magnis dis. Montes nascetur ridiculus mus donec rhoncus eros lobortis.',
	},
	{
		id: 6,
		restaurant: 'Restaurant 6',
		rating: 3,
		reviewer: 'Frank L.',
		date: 'Feb 1, 2026',
		body: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Adipiscing elit quisque faucibus ex sapien vitae pellentesque. Vitae pellentesque sem placerat in id cursus mi. Cursus mi pretium tellus duis convallis tempus leo. Tempus leo eu aenean sed diam urna tempor. Urna tempor pulvinar vivamus fringilla lacus nec metus.',
	},
	{
		id: 7,
		restaurant: 'Restaurant 7',
		rating: 5,
		reviewer: 'Grace K.',
		date: 'Feb 3, 2026',
		body: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Dolor sit amet consectetur adipiscing elit quisque faucibus.',
	},
	{
		id: 8,
		restaurant: 'Restaurant 8',
		rating: 4,
		reviewer: 'Henry W.',
		date: 'Feb 5, 2026',
		body: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos.',
	},
	{
		id: 9,
		restaurant: 'Restaurant 9',
		rating: 3,
		reviewer: 'Irene P.',
		date: 'Feb 6, 2026',
		body: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Sit amet consectetur adipiscing elit quisque faucibus ex. Adipiscing elit quisque faucibus ex sapien vitae pellentesque.',
	},
	{
		id: 10,
		restaurant: 'Restaurant 10',
		rating: 4,
		reviewer: 'Jack C.',
		date: 'Feb 7, 2026',
		body: 'Lorem ipsum dolor sit amet consectetur adipiscing elit. Elit quisque faucibus ex sapien vitae pellentesque sem. Sem placerat in id cursus mi pretium tellus. Tellus duis convallis tempus leo eu aenean sed. Sed diam urna tempor pulvinar vivamus fringilla lacus. Lacus nec metus bibendum egestas iaculis massa nisl. Nisl malesuada lacinia integer nunc posuere ut hendrerit.',
	},
];
